# Generated by Django 5.0.1 on 2024-02-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Main', '0002_danbooruimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('default_image', models.URLField()),
                ('trivia', models.TextField()),
            ],
        ),
    ]
