# Generated by Django 5.0.1 on 2024-02-16 05:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Main', '0003_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='ability',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='eye_color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='hair',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='trivia',
            field=models.TextField(blank=True),
        ),
    ]
