# Generated by Django 5.0.1 on 2024-02-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Main', '0005_danbooruimage_character_animecharacter_gamecharacter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecharacter',
            name='character',
        ),
        migrations.RemoveField(
            model_name='danbooruimage',
            name='character',
        ),
        migrations.AddField(
            model_name='character',
            name='category',
            field=models.CharField(choices=[('anime', 'Anime'), ('game', 'Game')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AnimeCharacter',
        ),
        migrations.DeleteModel(
            name='GameCharacter',
        ),
    ]
