# Generated by Django 5.0.1 on 2024-02-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Main', '0007_remove_character_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='default_image',
        ),
    ]
