# Generated by Django 5.0.1 on 2024-02-22 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Main', '0010_alter_character_options_character_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={},
        ),
        migrations.RemoveField(
            model_name='character',
            name='order',
        ),
    ]
