# Generated by Django 5.0.1 on 2024-02-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Main', '0012_character_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeCharacter',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('The_Main.character',),
        ),
        migrations.CreateModel(
            name='GameCharacter',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('The_Main.character',),
        ),
        migrations.AlterField(
            model_name='character',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
