# Generated by Django 5.0.1 on 2024-02-24 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Main', '0014_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='character',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='The_Main.character'),
            preserve_default=False,
        ),
    ]
