# Generated by Django 5.0.1 on 2024-02-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Main', '0016_rename_content_comment_text_alter_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
