# Generated by Django 5.0.1 on 2024-03-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Main', '0018_alter_character_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='VtuberCharacter',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('The_Main.character',),
        ),
        migrations.AlterField(
            model_name='character',
            name='category',
            field=models.CharField(choices=[('anime', 'Anime'), ('game', 'Game'), ('v-tuber', 'V-Tuber')], max_length=50),
        ),
    ]
