# Generated by Django 5.0.1 on 2024-03-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Main', '0019_vtubercharacter_alter_character_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='category',
            field=models.CharField(choices=[('anime', 'Anime'), ('game', 'Game'), ('v-tuber', 'V-Tuber')], max_length=50),
        ),
    ]
